name: Test-pywin32
# https://docs.github.com/en/actions/quickstart
# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    # Setup python
    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: 'pypy-3.9'
        architecture: x64
    - name: Python
      run: python --version
    - name: Platform
      run: |
        python -c "import platform;print('platform: ' + platform.platform());"
        python -c "import platform;print('system: ' + platform.system());"
        python -c "import platform;print('architecture: ' + platform.architecture());"
    - name: Python bit
      run: python -c "import sys;print(f'Is 64 bit if one - {sys.maxsize/2**63:f}')"

    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Print package list
      run: pip list
    - name: pywin32
      run: pip install pywin32
